### ISSUE TITLE
Figure out deployment

### ISSUE THREAD

**Issue by chingor13** [chingor13/white_elephant#3]
exrm?

**Comment by kylerippey** [comment]
I'm guessing this is about what we need:
- [x] Add exrm dep (#8)
- [ ] Upstart or runit script to boot the app (already done on DO instance?)
- [ ] Nginx config (already done on DO instance?)
- [ ] Write a deploy script. I'm thinking just a script that scp's the current release to a target machine, extracts it, and restarts the app. Example [here](https://hexdocs.pm/exrm/extra-deployment.html)

**Comment by chingor13** [comment]
We probably don't actually need nginx

**Comment by chingor13** [comment]
Am using edeliver & exrm
